"""starship model

Revision ID: 201486222f60
Revises: 9e9d60dd0528
Create Date: 2025-09-17 16:54:32.237642

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "201486222f60"
down_revision: Union[str, Sequence[str], None] = "9e9d60dd0528"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "starships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("cost_in_credits", sa.String(), nullable=False),
        sa.Column("length", sa.String(), nullable=False),
        sa.Column("max_atmosphering_speed", sa.String(), nullable=False),
        sa.Column("crew", sa.String(), nullable=False),
        sa.Column("passengers", sa.String(), nullable=False),
        sa.Column("cargo_capacity", sa.String(), nullable=False),
        sa.Column("consumables", sa.String(), nullable=False),
        sa.Column("hyperdrive_rating", sa.String(), nullable=False),
        sa.Column("mglt", sa.String(), nullable=False),
        sa.Column("starship_class", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(op.f("ix_starships_name"), "starships", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_starships_name"), table_name="starships")
    op.drop_table("starships")
    # ### end Alembic commands ###
