"""optional film fields

Revision ID: 57f39a766cd4
Revises: b14559c981d4
Create Date: 2025-09-17 18:20:59.620203

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57f39a766cd4"
down_revision: Union[str, Sequence[str], None] = "b14559c981d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("films", "url", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("films", "url", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
