"""nullable fields in Starship model

Revision ID: 8ee91e1caaf0
Revises: 57f39a766cd4
Create Date: 2025-09-18 14:53:07.048667

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ee91e1caaf0"
down_revision: Union[str, Sequence[str], None] = "57f39a766cd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("starships", "model", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "starships", "manufacturer", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "starships", "cost_in_credits", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("starships", "length", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "starships", "max_atmosphering_speed", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("starships", "crew", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "starships", "passengers", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "starships", "cargo_capacity", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "starships", "consumables", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "starships", "hyperdrive_rating", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("starships", "mglt", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "starships", "starship_class", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("starships", "url", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("starships", "url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "starships", "starship_class", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("starships", "mglt", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "starships", "hyperdrive_rating", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "starships", "consumables", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "starships", "cargo_capacity", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "starships", "passengers", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("starships", "crew", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "starships",
        "max_atmosphering_speed",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column("starships", "length", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "starships", "cost_in_credits", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "starships", "manufacturer", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("starships", "model", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
