"""character remove datetimes

Revision ID: ba49ec3c07a7
Revises: 1d817350e9c2
Create Date: 2025-09-17 16:41:55.908078

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ba49ec3c07a7"
down_revision: Union[str, Sequence[str], None] = "1d817350e9c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "created")
    op.drop_column("characters", "edited")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters",
        sa.Column("edited", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "characters",
        sa.Column(
            "created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
