"""add url in character model

Revision ID: d890a03306df
Revises: 8ee91e1caaf0
Create Date: 2025-09-18 16:04:58.366417

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d890a03306df"
down_revision: Union[str, Sequence[str], None] = "8ee91e1caaf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "url")
    # ### end Alembic commands ###
