"""Add characters table

Revision ID: dc2e28913fcd
Revises: a5d1feee2481
Create Date: 2025-09-16 23:33:48.726761

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc2e28913fcd"
down_revision: Union[str, Sequence[str], None] = "a5d1feee2481"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("hair_color", sa.String(), nullable=True),
        sa.Column("skin_color", sa.String(), nullable=True),
        sa.Column("eye_color", sa.String(), nullable=True),
        sa.Column("birth_year", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("edited", sa.DateTime(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.drop_table("characters")
    # ### end Alembic commands ###
